### ISSUE TITLE
ダークモードでメニューバーのアイコンの視認性が悪い

### ISSUE THREAD

**Issue by munierujp** [narikei/Charger-Information-for-Mac#2]
![スクリーンショット 2019-12-09 22 42 37](https://user-images.githubusercontent.com/20086673/70440313-43702280-1ad5-11ea-922b-11056a9bca92.png)

ダークモード用に白いアイコンもほしいです。

**Comment by narikei** [comment]
こちら対応しました！
https://github.com/narikei/Charger-Information-for-Mac/commit/fe244cd067e0b6c715db8526d83c2feff5f167ef
