### ISSUE TITLE
開いたトレイのメニューが5秒以内で勝手に閉じる

### ISSUE THREAD

**Issue by MichinariNukazawa** [narikei/Charger-Information-for-Mac#5]
# 再現の手順
アイコンクリックしてメニューを開く。
# 観察されたこと
０〜5秒程度でメニューが勝手に閉じる。

「メニューが勝手に閉じない・少なくとも10秒程度は開いた状態を維持する」動きを想定していました。
定時間等で自動で閉じるべきかどうかは難しいところですが、最悪1秒待たずに閉じるのは、好ましくないと感じています。

# その他
とりあえずで`updateMenu();`を`update`コールバック外に移動したところ、現象自体は起こらなくなるようです。ここでのMenu再構築の際に(electronから向こうのどこかの動作として)一旦閉じるようになっているのだと思います。ただこれでは状態表示の更新が反映されないようなので、もう一仕事とデザイン上の判断が必要そうです。
(閉じないように表示だけ更新する方法を見つける・Menuオープン中は更新しない・開き直す、などがあると思います。)

**Comment by narikei** [comment]
#1 もなんですが、自分の環境では発生せず、
どうも Catalina 以前と挙動が違いそうですね、、、

**Comment by MichinariNukazawa** [comment]
8206d82 により解決。
(状態変化時に発生しますが、新しいmacosxバージョンで発生しないこと、頻度が低くタイミング的にも実用上問題ないことから、解決として良いと思います。)
